config/routes.rb
Shorturl::Application.routes.draw do
  get 'contact/index'
  root :controller => 'urls', :action => 'all'
  resources :urls, :only => [:show, :new, :create]
end

app/models/url.rb
class Url < ActiveRecord::Base
  attr_accessible :url
  validates :url, :presence => true, :uniqueness => true, :length => { :minimum => 10, :maximum => 150 } , :uri => { :format => /(^$)|(^(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(([0-9]{1,5})?\/.*)?$)/ix }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
    @title = "Contact Us"
  end
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  def all # Show all shortened links
    @title = "All shorten URLs"
    @urls = Url.all
    respond_to do |format|
      format.html
    end
  end
  def new # Create a shortened link
    @title = "Create a URL shortened"
    @urls = Url.new
  end
  def create
    @urls = Url.new(params[:url])
    if @urls.save
      flash[:url_id] = @urls.id # Add a flash message
      redirect_to new_url_url
    else
      render :action => "new"
    end
  end
  def show # Redirect ID towards the URL
    @urls = Url.find(params[:id])
    @urls.nb_access += 1 # Count the number of visit for the link
    @urls.save
    redirect_to @urls.url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the title of the page (optimized for SEO)
  def title
    def_title = "Shorten URL - Free Online Service"
    if @title.nil?
      def_title
    else
      "#{@title} | #{def_title}"
    end
  end
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/views/contact/index.html.erb
<h2><%= @title %></h2>
<p>Contact me at: <em id="emailContact"></em></p>

<script>
    // Encode in ROT13 to prevent spam robots include the email address
    document.getElementById("emailContact").innerHTML = '<n uers="znvygb:cu7fbsgjner@tznvy.pbz?fhowrpg=Nobhg HEY Fubegrare - Envyf" ery="absbyybj">cu7fbsgjner@tznvy.pbz</n>'.replace(/[a-zA-Z]/g, function(c){return String.fromCharCode((c<="Z"?90:122)>=(c=c.charCodeAt(0)+13)?c:c-26);});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  <meta name="description" content="Online service to shorten your long URLs" />
  <meta name="keywords" content="short URL, URL, bitly, awesome, save, share, shorten" />
  <meta name="author" content="Pierre-Henry Soria" />
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

    <div id="container">
        <header><h1>pH7</h1></header>
            <nav id="top">
                <ul>
                    <li><%= link_to 'Home', root_path %></li>
                    <li><%= link_to 'Shorten URL', new_url_path %></li>
                    <li><%= link_to 'Contact Us',  contact_index_path %></li>
                </ul>
            </nav>

            <section class="content">
                <% if flash[:url_id].present? %>
                    <p>The shortened URL is available at <%= link_to url_url(flash[:url_id]), url_url(flash[:url_id]) %>.</p>
                <% end %>
                <%= yield %>
            </section>

        <footer>
            <p>By <strong><a href="http://ph-7.github.com">pH7</a></strong> &copy; <span id="copyrightYear"></span>.</p>
        </footer>
    </div>

    <script>
        // Retrieve the current date to the copyright
        document.getElementById('copyrightYear').innerHTML=(new Date).getFullYear();
    </script>
</body>
</html>

app/views/urls/all.erb
<h3><%= link_to 'Add new URL to shorten', new_url_path %></h3>

<% if !@urls.empty? %>
  <h1>List of recent URLs which have been shortened</h1>
  <ul>
    <% @urls.sort{|a,b| b.created_at <=> a.created_at }.each do |url| %>
      <li><%= url.created_at.strftime("%b %m, %Y") %> &nbsp;-&nbsp; <strong><%= url.url %></strong> via <strong><a href="<%= url_url(url.id) %>" rel="nofollow" target="_blank"><%= url.url %></a></strong> <em>(<%= url.nb_access %> access)</em></li>
    <% end %>
  </ul>
<% else %>
  <h2>Be the first one to shorten your URL!</h2>
<% end %>

app/views/urls/new.html.erb
<h1>Add a new URL</h1>
<%= form_for @urls do |form| %>
  <p>
    <%= form.label :url, "Your URL:" %>
    <%= form.url_field :url, :placeholder => 'Paste a link to shorten it', :autocomplete=> 'off', :required => 'required' %>
  </p>
  <% if @urls.errors[:url].any? %>
    <p class='error-messages'>
      The given url <%= @urls.errors[:url].to_sentence %>.
    </p>
  <% end %>
  <p class='buttons'>
    <%= form.submit "Shorten URL!" %>
  </p>
<% end %>